# Generated by Django 5.2.4 on 2025-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
