# Generated by Django 5.2.4 on 2025-08-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
